### ISSUE TITLE
Błąd

### ISSUE THREAD

**Issue by Dorii2003** [projectQOrganization/projectQ#12]
dcraft.24tm.pl/staty

nie ma stylu CSS, sam tekst... jak to naprawić?

**Comment by SlimaKCoder** [comment]
Nie jest to błąd kodu tylko zapewne błędna konfiguracja. W pliku "main.conf.php" masz ustawiony katalog główny na "/staty" zamiast "/"?

**Comment by Dorii2003** [comment]
Zmieniłem i w dalszym ciągu to samo

**Comment by SlimaKCoder** [comment]
Zmień na "/staty/", powinno pomóc.

**Comment by Dorii2003** [comment]
dzieki, dziala
