### ISSUE TITLE
Pusta strona albo błąd...

### ISSUE THREAD

**Issue by Dorii2003** [projectQOrganization/projectQ#14]
Witam, przed chwilą strona działała, a teraz jest cała pusta albo błąd:
Service Temporarily Unavailable

The server closed the connection without sending any data.

The server is temporarily unable to service your request due to maintenance downtime or capacity problems.

Due to heavy load on the server, connections may be temporarily blocked from locations that fetch an unusually high number of pages.

We apologize for the inconvenience.

===
dcraft.24tm.pl/staty

**Comment by SlimaKCoder** [comment]
Sprawdź jeszcze raz czy wszystkie dane podałeś poprawne. Jeżeli strona przestała działać "od tak" bez żadnych zmian to winę za to ponosi usługodawca (hosting).

**Comment by Dorii2003** [comment]
Zmieniałem parametry serwera minecraft i od tąd tak się dzieje.

**Comment by SlimaKCoder** [comment]
Może zwiesza całą maszynę?

**Comment by Dorii2003** [comment]
Możliwe, ale po zmianie opcji na false wszystko jest OK.

**Comment by Dorii2003** [comment]
Mam pytanie, w przypadku gdy uzywam FunnyGuilds, co ustawic w pliku mysql.conf.php

**Comment by SlimaKCoder** [comment]
Nie ważne co wstawisz. Strona ignoruje to pole dla FunnyGuild. Możesz wpisać "Jezdem fajny" ;D
