### ISSUE TITLE
Zmiana wielkości tabeli statystyk

### ISSUE THREAD

**Issue by Selcouth** [projectQOrganization/projectQ#17]
Hej, gdzie można zmienić rozmiar tabeli ze statystykami?

**Comment by TheMolkaPL** [comment]
W [tej](https://github.com/projectQOrganization/projectQ/blob/Development/class/Main.class.php) klasie. :)

**Comment by Selcouth** [comment]
W tej klasie zmieniłem już wcześniej wygląd a mi teraz chodzi o to jak zmienić rozmiar i wyśrodkować te tabele na środek. http://prntscr.com/65qoif

**Comment by TheMolkaPL** [comment]
Użyj tagu
```html
<center>...</center>
```

**Comment by Selcouth** [comment]
W index.php?

**Comment by Selcouth** [comment]
Po wstawieniu w index.php nie środkuje sie tabela

**Comment by SlimaKCoder** [comment]
Najlepiej daj link do strony to zobaczę jak to u Ciebie wygląda.

**Comment by Selcouth** [comment]
Mam stronę na localhost teraz

**Comment by Selcouth** [comment]
Nie da się jakoś tego zrobić gdy tego nie widzisz?

**Comment by SlimaKCoder** [comment]
Gdy strona jest online to można wyświetlić ją w przeglądarce i edytować w trybie Live.

**Comment by Selcouth** [comment]
Mogę ci ewentualnie pliki wysłać

**Comment by Selcouth** [comment]
http://www.speedyshare.com/rEBnx/strona.rar

**Comment by SlimaKCoder** [comment]
Szczerze to nie chce mi się ich ściągać i odpalać wrzucać na serwer ;) Wstaw na jakiś darmowy hosting czy coś ;D

**Comment by Selcouth** [comment]
Wstawiłem na hostinger i strona wgl nie ma wyglądu css.

**Comment by Selcouth** [comment]
No to jak, pomożesz mi?
